# Configuracion de conexion a la base de datos
# ---------------------------------------------------------------
# Para usar la BBDD LOCAL (XAMPP, Docker Desktop, etc.):
#   db.ip=localhost
#
# Para usar la BBDD REMOTA en AWS EC2 (instancia con LAMP Docker):
#   db.ip=52.87.132.150
#
# ---------------------------------------------------------------

db.ip=52.87.132.150
db.port=3306
db.name=Muudle
db.user=admin
db.password=1234
